Check if particles are overlapping
JuliaWaveScattering/MultipleScattering.jl pull request #41
Opened 2022-08-06 19:32 UTC by Kevish-Napal

Hey, finally found how to interact with Pkg and git correctly!

I wrote the first function isempty(Origins,Radii) where Origins and Radii are vectors so one can easily check this function without having to define particles.

Kevish

2022-08-06 22:21 UTC, jondea requested changes
Hi @Kevish-Napal, massive thanks for your contribution, this looks like a useful check, so thank you for implementing it. Also, great work fighting `Pkg` and `git`, I promise you're almost there to your first PR! 

One overall comment is that the convention in this package (and most Julia packages) is to use `snake_case` for variable names and `CamelCase` for types and modules. Otherwise, this looks like a great first PR.

2022-08-06 22:21 UTC, jondea commented on src/simulation.jl
> +function isoverlapping(Origins,Radii)
I would interpret `isoverlapping` to return true if argument 1 is overlapping with argument 2. Would  `anyoverlapping` more clearly describe checking between all the pairs of particles?

2022-08-08 16:55 UTC, Kevish-Napal commented on src/simulation.jl
> +function isoverlapping(Origins,Radii)
Hi @jondea , thanks for your comments! I made some changes accordingly.

2022-08-08 17:06 UTC, Kevish-Napal commented on src/simulation.jl
> +        return true
I renamed "isoverlapping" to "overlapping_pairs" which returns a vector of the overlapping pairs instead of true/false. The error is now thrown in the run function.

2022-08-08 22:17 UTC, jondea requested changes
Thank you for your changes! Two of the comments weren't full addressed, I've tried to add a bit more detail, let me know if your have any questions.

2022-08-08 22:17 UTC, jondea commented on src/simulation.jl
>          return
This code is still unreachable, it will never be run because `@error` throws an error on line 93. Either move the error until after this or remove it.

2022-08-08 22:17 UTC, jondea commented on src/simulation.jl
> +    Origins = origin.(P)
`Origins`, `Radii` and `P` are all variables, they should be `snake_case` not `CamelCase`.

2022-08-09 07:38 UTC, Kevish-Napal commented on src/simulation.jl
>          return
Hello @jondea, a few remarks here: 

on my machine, all of the code you highlighted appearing after @error was run. @error was only displaying the message in parenthesis. The function would stop running because of the "return" in the loop.

To obtain the expected behavior, I replaced @error() with error(). I hope this was the  correct solution.

2022-08-09 07:39 UTC, Kevish-Napal commented on src/simulation.jl
> +    Origins = origin.(P)
My bad, I forgot this one. Thanks!

2022-08-09 21:52 UTC, jondea commented on src/simulation.jl
>          return
I'm really sorry, I forgot that `@error` was just a logging macro, I thought it threw an error. Thank you for clarifying. I don't have a strong opinion on which is better, in the rest of the codebase I think we tend to throw errors rather than use `@error` so maybe stick with this for now.

Also, the error message telling the user how to get the overlapping particles is a great idea, thanks!

2022-08-09 21:54 UTC, jondea approved these changes
It looks good to me, thank you again! I'll let @arturgower have a quick look over and merge it if he's happy.

2023-08-07 08:35 UTC, merged